# This module exposes the outputs generated by shared setup so that *.tftest.hcl/*.tofutest.hcl files can access them
# without creating the same set of resources for each test case.
terraform {
  required_version = ">= 1.2"
}

data "terraform_remote_state" "setup" {
  backend = "local"

  config = {
    path = format("%s/../terraform.tfstate", path.module)
  }
}
