# These github actions will perform linting using pre-commit.
# yamllint disable rule:line-length
# spell-checker: disable
---
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches-ignore:
      - main
permissions:
  contents: read
  pull-requests: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: dev
    steps:
      - uses: actions/checkout@v4
      - name: install talisman
        run: |
          sudo curl -sLo /usr/local/bin/talisman https://github.com/thoughtworks/talisman/releases/download/v1.32.0/talisman_linux_amd64
          sudo chmod 0755 /usr/local/bin/talisman
      - name: Install terraform-docs
        run: |
          sudo sh -c 'curl -sL https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz | tar xzf - -C /usr/local/bin'
          sudo chmod 0755 /usr/local/bin/terraform-docs
      - name: Install tflint
        run: |
          curl -sLO https://github.com/terraform-linters/tflint/releases/download/v0.55.0/tflint_linux_amd64.zip
          unzip tflint_linux_amd64.zip && rm tflint_linux_amd64.zip
          sudo mv tflint /usr/local/bin/tflint
          sudo chmod 0755 /usr/local/bin/tflint
      - name: install opentofu
        run: |
          sudo sh -c 'curl -sL https://github.com/opentofu/opentofu/releases/download/v1.9.0/tofu_1.9.0_linux_amd64.tar.gz | tar xzf - -C /usr/local/bin tofu'
          sudo chmod 0755 /usr/local/bin/tofu
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Pre-commit
        uses: pre-commit/action@v3.0.1
